### ISSUE TITLE
Clarification on Updating Test Cases on GitHub

### ISSUE THREAD

**Issue by Uranustrong** [NTU-SP/SP2024_HW2_release#1]
Dear TAs,

I hope this message finds you well. I am writing to confirm if we should push the updated test cases to our own GitHub repository as part of the assignment requirements.

Thank you very much for your guidance and assistance.

Best regards,
宋和峻敬上

**Comment by Saiko0324** [comment]
Hi,

No, we will have our own testcases when judging, your test case state will not affect your grading, and you may do as you please

Best Regards,
SP TA 迪善
